[project]
name = "try-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.5.0",
    "anthropic>=0.51.0",
    "fastapi[standard]>=0.115.12",
    "yfinance>=0.2.61",
]
